version: '3.0'

services:
  flask:
    build: .
    restart: unless-stopped
    volumes:
      - "./:/app"
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: altayatalay/db:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
